#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/hyperspell/hyperspell-go,github.com/stainless-sdks/hyperspell-go"

echo "==> Building hyperspell"
go build ./cmd/hyperspell
