#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/hyperspell/hyperspell-go,github.com/stainless-sdks/hyperspell-go"

REPLACEMENT="${1:-"../hyperspell-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/hyperspell/hyperspell-go="$REPLACEMENT"
go mod tidy -e
